create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (optional for local dev, but good practice)
alter table todos enable row level security;
create policy "public_access" on todos for all using (true);